FROM faddat/sos-lite

# Add seeds and such after doing gaia.
# I will prototype the rest of this on gaia.
RUN echo cosmos > /etc/hostname && \
		pacman -Syyu --noconfirm docker-compose zerotier-one
#		echo "docker run am3o/cosmos" >> /usr/local/bin/firstboot.sh
# TODO: docker-compose
